spring:
  application:
    name: zuul
server:
  port: 3001
eureka:
  client:
    service-url:
      #eureka 服务器的部署位置
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka

zuul:
  routes:
    item-service: /item-service/**
    user-service: /user-service/**
    order-service: /order-service/**
  retryable: true
ribbon:  
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
  